### ISSUE TITLE
Size issues when cross compiling

### ISSUE THREAD

**Issue by winding-lines** [boncheolgu/tflite-rs#11]
I am trying to cross compile`tflite-rs` for a Raspberry Pi board. I am running in the following error. Do you have some pointers on how to make progress?

```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
   --> src/interpreter.rs:318:17
    |
318 |                 quantization as "TfLiteQuantizationParams",
    |                 ^^^^^^^^^^^^
    |
    = note: source type: `&bindings::root::TfLiteQuantizationParams` (32 bits)
    = note: target type: `[u8; 8]` (64 bits)
```

Many thanks!

**Comment by winding-lines** [comment]
I made some progress on this, the following commit fixes compilation

https://github.com/winding-lines/tflite-rs/commit/73a10e8c6185e3bf03eec9282579cab99ebf3283

The issue seems to be that the quantization parameters are expected to be passed by value (a 64bit struct) while a pointer is being passed in. On 32 bits systems the error shows up.

I don't have enough experience with the code yet to understand if the fix above is correct from a functional standpoint, let me know if you want me to submit a PR.

**Comment by boncheolgu** [comment]
I think you have pointed right. Please submit a PR. Thanks!

**Comment by winding-lines** [comment]
Many thanks @boncheolgu! 

Is there any chance you could publish to crates.io?

**Comment by boncheolgu** [comment]
@winding-lines sure, I'll do it right now.
