### ISSUE TITLE
Use git submodule instead of downloading?

### ISSUE THREAD

**Issue by tylerhawkes** [boncheolgu/tflite-rs#6]
I noticed that in commit `047e39e8564d3805a785071830f44a409730f90e` you changed from using a submodule to downloading the releases. This adds a lot of overhead to cross-compiling builds with the need to compile all the crates for the host to download and verify. Since cargo already packages up submodules with the rest of the code, would you be open to a pull request that goes back to using them?

**Comment by boncheolgu** [comment]
I didn't know that cargo would do that for submodules. I am glad to see a PR which uses a submodule. Thanks.
