### ISSUE TITLE
Rationale of submodule 'downloads'

### ISSUE THREAD

**Issue by Finfalter** [boncheolgu/tflite-rs#60]
I would kindly like to ask for the rationale of the _**downloads**_ submodule. I know that named submodule comprises necessary dependencies as _flatbuffers_ and others. However, these dependencies might also be provisioned in a different way, for example by use of the script _**tensorflow/lite/tools/make/download_dependencies.sh**_ which is part of Tensorflow's sources. Named script may be called from within the build script. I have a fork of tflite-rs which does this (actually forked from ionosnetworks tflite-rs which is a fork of this project). 

Did you consider different possibilities to provision the dependencies? Did you maybe prefer a provisioning mechanism via a separate submodule like _**downloads**_ over downloading dependencies directly in the build script? If so, why?

Thank you very much for your feedback.

**Comment by boncheolgu** [comment]
If I remember correctly, I tried to download the dependencies in build.rs to reduce the crate size, but 'cargo publish' didn't allow it due to somewhat security reason.
Maybe you can try `cargo publish --dry-run` in your fork.
If successful, I will consider adopting the method you suggested.
Thanks!

**Comment by Finfalter** [comment]
Unfortunately, `cargo publish --dry-run --allow-dirty` stops with errors (`--dry-run` because of cloned **submodule/tensorflow**) where 
```
cargo clean
cargo build
# and optionally
cargo test
```
run seamlessly. In case I get it working, I will drop you a note.
